* Encoding: UTF-8.
* Project  : Prevalence and Associated Factors of Depression Among Type 1 Diabetes Patients Attending Atbra Teaching Hospital, Nahr Al-Nil State, Sudan - 2025
* Script   : Full Statistical Analysis
* Author   : Abdulrahman Sirelkhatim
* Date     : October 2025
*
* NOTE: Update the FILE path in the GET DATA command below before running.
* Encoding: UTF-8.

GET DATA
  /TYPE=XLSX
  /FILE='C:\path\to\1_data\cleaned\cleaned_data.xlsx'
  /SHEET=name 'Sheet1'
  /READNAMES=ON.
CACHE.
EXECUTE.

* Recode HDRS text responses to numeric scores.
* Each HDRS item encodes its score as the leading digit (e.g., "2= Moderate" -> 2).

DO REPEAT src=HDRS1_STR HDRS2_STR HDRS3_STR HDRS4_STR HDRS5_STR HDRS6_STR
           HDRS7_STR HDRS8_STR HDRS9_STR HDRS10_STR HDRS11_STR HDRS12_STR
           HDRS13_STR HDRS14_STR HDRS15_STR HDRS16_STR HDRS17_STR
        /tgt=HDRS1_NUM HDRS2_NUM HDRS3_NUM HDRS4_NUM HDRS5_NUM HDRS6_NUM
             HDRS7_NUM HDRS8_NUM HDRS9_NUM HDRS10_NUM HDRS11_NUM HDRS12_NUM
             HDRS13_NUM HDRS14_NUM HDRS15_NUM HDRS16_NUM HDRS17_NUM.
  COMPUTE tgt = NUMBER(SUBSTR(src, 1, 1), F1.0).
END REPEAT.
EXECUTE.

* Variable labels for HDRS numeric items.
VARIABLE LABELS
  HDRS1_NUM  'HDRS Item 1: Depressed Mood'
  HDRS2_NUM  'HDRS Item 2: Feelings of Guilt'
  HDRS3_NUM  'HDRS Item 3: Suicidal Thoughts'
  HDRS4_NUM  'HDRS Item 4: Insomnia - Early'
  HDRS5_NUM  'HDRS Item 5: Insomnia - Middle'
  HDRS6_NUM  'HDRS Item 6: Insomnia - Late'
  HDRS7_NUM  'HDRS Item 7: Work and Activities'
  HDRS8_NUM  'HDRS Item 8: Psychomotor Retardation'
  HDRS9_NUM  'HDRS Item 9: Psychomotor Agitation'
  HDRS10_NUM 'HDRS Item 10: Anxiety - Psychic'
  HDRS11_NUM 'HDRS Item 11: Anxiety - Somatic'
  HDRS12_NUM 'HDRS Item 12: Gastrointestinal Symptoms'
  HDRS13_NUM 'HDRS Item 13: Somatic Symptoms - General'
  HDRS14_NUM 'HDRS Item 14: Genital Symptoms'
  HDRS15_NUM 'HDRS Item 15: Hypochondriasis'
  HDRS16_NUM 'HDRS Item 16: Weight Loss'
  HDRS17_NUM 'HDRS Item 17: Insight'.

* Compute HDRS total score.
COMPUTE HDRS_TOTAL = SUM(HDRS1_NUM TO HDRS17_NUM).
VARIABLE LABELS HDRS_TOTAL 'HDRS-17 Total Score (0-52)'.
EXECUTE.

* Binary depression status (HDRS > 7 = depressed).
RECODE HDRS_TOTAL (MISSING=SYSMIS) (LO THRU 7=0) (8 THRU HI=1) INTO DEPRESSION_STATUS.
VARIABLE LABELS DEPRESSION_STATUS 'Depression Status (1=Depressed, 0=No Depression)'.
VALUE LABELS DEPRESSION_STATUS 0 'No Depression' 1 'Depressed'.
EXECUTE.

* Ordinal depression severity levels (per HDRS cut-offs).
RECODE HDRS_TOTAL (MISSING=SYSMIS)
  (LO THRU 7=1) (8 THRU 16=2) (17 THRU 24=3) (25 THRU HI=4) INTO DEPRESSION_LEVEL.
VARIABLE LABELS DEPRESSION_LEVEL 'Depression Severity Level'.
VALUE LABELS DEPRESSION_LEVEL
  1 'No Depression (0-7)'
  2 'Mild (8-16)'
  3 'Moderate (17-24)'
  4 'Severe (>=25)'.
EXECUTE.

* Numeric recode for categorical variables.
RECODE GENDER ('Male'=1) ('Female'=2) INTO GENDER_NUM.
VALUE LABELS GENDER_NUM 1 'Male' 2 'Female'.

RECODE MARITAL ('Single'=1) ('Married'=2) ('Divorced'=3) ('Widowed'=4) INTO MARITAL_NUM.
VALUE LABELS MARITAL_NUM 1 'Single' 2 'Married' 3 'Divorced' 4 'Widowed'.

RECODE EDUCATN
  ('No formal education'=1) ('Primary School'=2) ('Secondary School'=3) ('Higher Education'=4)
  INTO EDUCATN_NUM.
VALUE LABELS EDUCATN_NUM 1 'No formal education' 2 'Primary School' 3 'Secondary School' 4 'Higher Education'.

RECODE EMPLOY ('Employed'=1) ('Unemployed'=2) ('Student'=3) ('Housewife'=4) INTO EMPLOY_NUM.
VALUE LABELS EMPLOY_NUM 1 'Employed' 2 'Unemployed' 3 'Student' 4 'Housewife'.

RECODE TREATMNT
  ('Insulin injections only'=1) ('Insulin + oral medication'=2)
  ('Diet and exercise only'=3) INTO TREATMNT_NUM.
VALUE LABELS TREATMNT_NUM 1 'Insulin only' 2 'Insulin + oral' 3 'Diet/exercise only'.

RECODE MED_ADHR
  ('Always'=5) ('Most of the time'=4) ('Sometimes'=3) ('Rarely'=2) ('Never'=1)
  INTO MED_ADHR_NUM.
VALUE LABELS MED_ADHR_NUM 1 'Never' 2 'Rarely' 3 'Sometimes' 4 'Most of the time' 5 'Always'.

RECODE BS_MONIT
  ('Daily'=5) ('Several times a week'=4) ('Once a week'=3) ('Rarely'=2) ('Never'=1)
  INTO BS_MONIT_NUM.
VALUE LABELS BS_MONIT_NUM 1 'Never' 2 'Rarely' 3 'Once a week' 4 'Several times/week' 5 'Daily'.

RECODE LAST_A1C
  ('Less than 3 months ago'=4) ('3-6 months ago'=3) ('More than 6 months ago'=2) ('Never'=1)
  INTO LAST_A1C_NUM.
VALUE LABELS LAST_A1C_NUM 1 'Never' 2 '>6 months ago' 3 '3-6 months ago' 4 '<3 months ago'.

RECODE GLY_CTRL ('Good'=1) ('Not sure'=2) ('Poor'=3) INTO GLY_CTRL_NUM.
VALUE LABELS GLY_CTRL_NUM 1 'Good' 2 'Not sure' 3 'Poor'.

RECODE DOC_VISIT
  ('Every 1-3 months'=5) ('Every 4-6 months'=4) ('Once a year'=3)
  ('Only when problems arise'=2) ('Never'=1) INTO DOC_VISIT_NUM.
VALUE LABELS DOC_VISIT_NUM 1 'Never' 2 'When problems arise' 3 'Once a year' 4 'Every 4-6 months' 5 'Every 1-3 months'.
EXECUTE.

* Age and duration groups.
RECODE AGE (LO THRU 19=1) (20 THRU 39=2) (40 THRU HI=3) INTO AGE_GROUP.
VALUE LABELS AGE_GROUP 1 'Under 20' 2 '20-39' 3 '40 and Over'.

RECODE DIAB_DUR (LO THRU 5=1) (6 THRU 15=2) (16 THRU HI=3) INTO DURATION_GROUP.
VALUE LABELS DURATION_GROUP 1 '0-5 Years' 2 '6-15 Years' 3 'Over 15 Years'.
EXECUTE.

* Any complication flag.
COMPUTE ANY_COMPLICATION = 0.
IF (COMP_NEUR=1 OR COMP_NEPH=1 OR COMP_RET=1 OR COMP_FOOT=1 OR COMP_CVD=1)
  ANY_COMPLICATION = 1.
VALUE LABELS ANY_COMPLICATION 0 'No Complication' 1 'Any Complication'.
EXECUTE.

* Reliability analysis: HDRS-17 scale.
RELIABILITY
  /VARIABLES=HDRS1_NUM HDRS2_NUM HDRS3_NUM HDRS4_NUM HDRS5_NUM HDRS6_NUM
             HDRS7_NUM HDRS8_NUM HDRS9_NUM HDRS10_NUM HDRS11_NUM HDRS12_NUM
             HDRS13_NUM HDRS14_NUM HDRS15_NUM HDRS16_NUM HDRS17_NUM
  /SCALE('HDRS-17') ALL
  /MODEL=ALPHA
  /STATISTICS=SCALE CORR
  /SUMMARY=TOTAL.

* Descriptive statistics: continuous variables.
DESCRIPTIVES VARIABLES=AGE DIAB_DUR HDRS_TOTAL
  /STATISTICS=MEAN STDDEV MIN MAX.

* Descriptive statistics: categorical and demographic variables.
FREQUENCIES VARIABLES=GENDER_NUM MARITAL_NUM EDUCATN_NUM EMPLOY_NUM
  TREATMNT_NUM MED_ADHR_NUM BS_MONIT_NUM LAST_A1C_NUM GLY_CTRL_NUM DOC_VISIT_NUM
  COMP_NEUR COMP_NEPH COMP_RET COMP_FOOT COMP_CVD ANY_COMPLICATION
  DEPRESSION_STATUS DEPRESSION_LEVEL AGE_GROUP DURATION_GROUP
  /STATISTICS=MODE
  /BARCHART.

* Pearson correlations: age, diabetes duration, HDRS total.
CORRELATIONS
  /VARIABLES=AGE DIAB_DUR HDRS_TOTAL
  /PRINT=TWOTAIL NOSIG.

* Chi-square tests: depression status vs categorical variables.
CROSSTABS /TABLES=GENDER_NUM BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=MARITAL_NUM BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=EDUCATN_NUM BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=EMPLOY_NUM BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=TREATMNT_NUM BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=MED_ADHR_NUM BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=BS_MONIT_NUM BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=LAST_A1C_NUM BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=GLY_CTRL_NUM BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=DOC_VISIT_NUM BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=COMP_NEUR BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=COMP_NEPH BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=COMP_RET BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=COMP_FOOT BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.
CROSSTABS /TABLES=COMP_CVD BY DEPRESSION_STATUS /CELLS=COUNT ROW /STATISTICS=CHISQ.

* Independent samples t-test: HDRS total by gender.
T-TEST GROUPS=GENDER_NUM(1 2) /VARIABLES=HDRS_TOTAL /MISSING=ANALYSIS /CRITERIA=CI(.95).

* One-way ANOVA: HDRS total by age group, duration group, and education.
ONEWAY HDRS_TOTAL BY AGE_GROUP /STATISTICS DESCRIPTIVES /MISSING ANALYSIS /POSTHOC=BONFERRONI ALPHA(0.05).
ONEWAY HDRS_TOTAL BY DURATION_GROUP /STATISTICS DESCRIPTIVES /MISSING ANALYSIS /POSTHOC=BONFERRONI ALPHA(0.05).
ONEWAY HDRS_TOTAL BY EDUCATN_NUM /STATISTICS DESCRIPTIVES /MISSING ANALYSIS /POSTHOC=BONFERRONI ALPHA(0.05).

* Multiple linear regression: predictors of HDRS total score.
REGRESSION
  /DESCRIPTIVES=MEAN STDDEV CORR
  /MISSING LISTWISE
  /STATISTICS COEFF OUTS R ANOVA COLLIN TOL CHANGE
  /CRITERIA=PIN(.05) POUT(.10)
  /DEPENDENT HDRS_TOTAL
  /METHOD=ENTER AGE_GROUP DURATION_GROUP GENDER_NUM MARITAL_NUM EDUCATN_NUM EMPLOY_NUM
    TREATMNT_NUM MED_ADHR_NUM BS_MONIT_NUM LAST_A1C_NUM GLY_CTRL_NUM DOC_VISIT_NUM
    COMP_NEUR COMP_NEPH COMP_RET COMP_FOOT COMP_CVD.

* Binary logistic regression: predictors of depression diagnosis.
LOGISTIC REGRESSION VAR=DEPRESSION_STATUS
  /METHOD=ENTER AGE_GROUP DURATION_GROUP GENDER_NUM MARITAL_NUM EDUCATN_NUM EMPLOY_NUM
    TREATMNT_NUM MED_ADHR_NUM BS_MONIT_NUM LAST_A1C_NUM GLY_CTRL_NUM DOC_VISIT_NUM
    COMP_NEUR COMP_NEPH COMP_RET COMP_FOOT COMP_CVD
  /PRINT=GOODFIT CI(95).

* NOTE: Update the OUTFILE path below before saving.
SAVE OUTFILE='C:\path\to\1_data\cleaned\cleaned_data.sav' /COMPRESSED.
EXECUTE.
